[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]
dotenv = ".env"

ffi = true


# remapping = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
